apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
  namespace: hipster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadgenerator
  template:
    metadata:
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: 'true'
      labels:
        app: loadgenerator
    spec:
      containers:
      - env:
        - name: FRONTEND_ADDR
          value: frontend:80
        - name: USERS
          value: '10'
        image: ghcr.io/nephelesoftware/hipster-loadgenerator:vortiq-d727b50
        imagePullPolicy: IfNotPresent
        name: main
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 300m
            memory: 256Mi
      imagePullSecrets:
      - name: hipster-ghcr-pull
      restartPolicy: Always
      terminationGracePeriodSeconds: 5
